# Generated by Django 4.0.3 on 2022-03-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnomina', '0004_alter_cargo_options_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
