# Generated by Django 4.0.3 on 2022-03-25 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appnomina', '0008_alter_empleado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnomina.cargo', verbose_name='Seleccionar...'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnomina.departamento', verbose_name='Seleccionar...'),
        ),
    ]
