# Generated by Django 4.0.3 on 2022-03-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnomina', '0010_alter_empleado_cargo_alter_empleado_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='estado',
            new_name='activo',
        ),
    ]
